/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./**/*.html"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e5e1e4",
        "on-tertiary-container": "#6b4700",
        "inverse-primary": "#00677f",
        "on-primary-fixed": "#001f28",
        "primary": "#a4e6ff",
        "tertiary": "#ffd59c",
        "secondary": "#ecb2ff",
        "surface-dim": "#131315",
        "on-surface-variant": "#bbc9cf",
        "on-tertiary-fixed-variant": "#624000",
        "on-tertiary": "#442b00",
        "secondary-fixed-dim": "#ecb2ff",
        "on-secondary-container": "#480063",
        "surface-container-low": "#1c1b1d",
        "background": "#131315",
        "surface-variant": "#353437",
        "secondary-fixed": "#f8d8ff",
        "primary-fixed-dim": "#4cd6ff",
        "on-secondary-fixed-variant": "#74009f",
        "on-background": "#e5e1e4",
        "on-primary": "#003543",
        "surface-tint": "#4cd6ff",
        "on-primary-container": "#00566a",
        "surface": "#131315",
        "outline": "#859399",
        "on-tertiary-fixed": "#291800",
        "error": "#ffb4ab",
        "surface-bright": "#39393b",
        "primary-fixed": "#b7eaff",
        "on-secondary-fixed": "#320047",
        "on-secondary": "#520071",
        "on-primary-fixed-variant": "#004e60",
        "error-container": "#93000a",
        "surface-container": "#201f21",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#353437",
        "surface-container-high": "#2a2a2c",
        "tertiary-container": "#feb127",
        "on-error": "#690005",
        "surface-container-lowest": "#0e0e10",
        "tertiary-fixed-dim": "#ffba49",
        "on-surface": "#e5e1e4",
        "secondary-container": "#cf5cff",
        "outline-variant": "#3c494e",
        "tertiary-fixed": "#ffddb1",
        "inverse-on-surface": "#313032",
        "primary-container": "#00d1ff"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
